[Feature/APP-103] new setting: enforce native installer
Aptoide/aptoide-client-v8 pull request #1427
Opened 2020-11-27 15:51 UTC by jdandrade

**What does this PR do?**

   new setting - enforce native installer. This will allow Xiaomi users to recover from the state of not being able to install any application in the app because of the PackageInstaller

**Database changed?**

  No

**Where should the reviewer start?**

- [ ] settings.xml
- [ ] AppBundlesVisibilityManager.java
- [ ] InstallManager.java

**How should this be manually tested?**

  - Test installations with both setting on/off on Xiaomi and non-xiaomi devices.

**What are the relevant tickets?**

  Tickets related to this pull-request: [APP-103](https://aptoide.atlassian.net/browse/APP-103)

**Code Review Checklist**

- [ ] Documentation on public interfaces
- [ ] Database changed? If yes - Migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] New Kotlin code has unit tests
- [ ] New flows in presenters unit tests
- [ ] Mappers/Validators with any kind of logic unit tests
- [ ] Functional tests pass

2020-12-02 20:19 UTC, phillipsgoncalves requested changes

2020-12-02 20:19 UTC, phillipsgoncalves commented on app/src/main/java/cm/aptoide/pt/install/InstallManager.java
> +    boolean shouldForceDefaultInstall =
Why not use the settingsProvider you created here? You have a method for isEnforceNativeInstaller() and you wouldn't need to extract the variable either

2020-12-02 20:19 UTC, phillipsgoncalves commented on app/src/main/java/cm/aptoide/pt/install/InstallManager.java
> +        sharedPreferences.getBoolean(ManagedKeys.ENFORCE_NATIVE_INSTALLER_KEY, false);
same as above

2020-12-02 20:19 UTC, phillipsgoncalves commented on app/src/main/java/cm/aptoide/pt/install/InstallManager.java
> +        sharedPreferences.getBoolean(ManagedKeys.ENFORCE_NATIVE_INSTALLER_KEY, false);
same as above

2020-12-02 20:19 UTC, phillipsgoncalves commented on app/src/main/java/cm/aptoide/pt/install/InstallManager.java
> +        sharedPreferences.getBoolean(ManagedKeys.ENFORCE_NATIVE_INSTALLER_KEY, false);
Also here, note for the future, but forceSplitInstall and forceDefaultInstall are mutually exclusive as we can only use one type of install for each install.

2020-12-09 12:24 UTC, phillipsgoncalves commented
After some tests, I noticed the following:
- after changing the installer setting should we refresh the updates automatically? This is important because after changing the setting, if we navigate to the apps section, we will still have old updates/updates with app bundles which will not be installed.
- some updates are stuck on installing even after the installation finished (wether with app not installed or success) (this happened on my pixel 5, could not reproduce on my xiami as on my xiaomi device i could not see those apps)

2020-12-10 14:23 UTC, jdandrade commented
> * after changing the installer setting should we refresh the updates automatically? This is important because after changing the setting, if we navigate to the apps section, we will still have old updates/updates with app bundles which will not be installed.

Good question. This feature is to be a fallback to a really bad experience, a lifeboat for users stuck on this situation. Even if the UX is not optimal this users will most likely be in contact with us about the issue so we can just tell them to refresh/clear data on the device.

2020-12-10 14:26 UTC, merged