[Feature/APP-428] Promotional cards: News
Aptoide/aptoide-client-v8 pull request #1458
Opened 2021-06-09 16:02 UTC by jdandrade

**What does this PR do?**

   This PR is the implementation of the promotional card: NEWS  

**Database changed?**

   No

**Where should the reviewer start?**

- [ ] BundlesResponseMapper.java

**How should this be manually tested?**

  Ask me for charles rewrite (for promotional card). Test views affected by the assets changes.

**What are the relevant tickets?**

  Tickets related to this pull-request: [APP-261](https://aptoide.atlassian.net/browse/APP-261) [APP-307](https://aptoide.atlassian.net/browse/APP-307)

**Code Review Checklist**

- [ ] Documentation on public interfaces
- [ ] Database changed? If yes - Migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] New Kotlin code has unit tests
- [ ] New flows in presenters unit tests
- [ ] Mappers/Validators with any kind of logic unit tests
- [ ] Functional tests pass

2021-06-16 16:40 UTC, phillipsgoncalves requested changes

2021-06-16 16:40 UTC, phillipsgoncalves commented on app/src/main/res/layout/card_news.xml
> +          android:textColor="@color/white"
could use white textviewstyle ?

2021-06-17 16:57 UTC, jdandrade commented on app/src/main/res/layout/card_news.xml
> +<!--    <ImageView-->
done :+1:

2021-06-17 16:58 UTC, jdandrade commented on app/src/main/res/layout/card_news.xml
> +          android:textColor="@color/white"
yup, corrected.

2021-06-17 17:18 UTC, merged