Feature/app 430 promotional cards event
Aptoide/aptoide-client-v8 pull request #1462
Opened 2021-06-17 16:48 UTC by jdandrade

THIS PR DEPENDS ON https://github.com/Aptoide/aptoide-client-v8/pull/1459

**What does this PR do?**

   This PR is the implementation of the promotional card: EVENT

**Database changed?**

   No

**Where should the reviewer start?**

- [ ] BundlesResponseMapper.java

**How should this be manually tested?**

  Ask me for charles rewrite (for promotional card). Test views affected by the assets changes.

**What are the relevant tickets?**

  Tickets related to this pull-request: [APP-430](https://aptoide.atlassian.net/browse/APP-430)

**Code Review Checklist**

- [ ] Documentation on public interfaces
- [ ] Database changed? If yes - Migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] New Kotlin code has unit tests
- [ ] New flows in presenters unit tests
- [ ] Mappers/Validators with any kind of logic unit tests
- [ ] Functional tests pass

2021-06-17 22:04 UTC, phillipsgoncalves requested changes
Also, noticed that the Skeletons of the textivews have the wrong color on the dark theme

2021-06-17 22:05 UTC, phillipsgoncalves commented
Putting the comment here, so it does not get missed along with the review ones: 
"Also, noticed that the Skeletons of the textivews have the wrong color on the dark theme - they have the light one"

2021-06-21 08:49 UTC, jdandrade commented on app/src/main/res/layout/card_event.xml
> +        app:cardBackgroundColor="#3c3c3c"
In the future we shall review this.

2021-06-21 13:58 UTC, jdandrade commented on app/src/main/res/layout/card_event.xml
> +        android:textColor="@color/green"
Done

2021-06-21 13:58 UTC, jdandrade commented on app/src/main/res/layout/card_event.xml
> +          android:textColor="@color/white"
Done

2021-06-23 16:01 UTC, merged