[APP-1310] flavour cobrand
Aptoide/aptoide-client-v8 pull request #1551
Opened 2022-08-31 08:31 UTC by phillipsgoncalves

**What does this PR do?**

This PR aims at creating the cobrand flavour as well as making some configurations.
Changes package name, version name, theme (only putting background with the blue color as the design is not defined yet). 

**Database changed?**

 No

**Where should the reviewer start?**

- [ ] BUILD.GRADLE.KTS (app)

**How should this be manually tested?**

  Run the app in the different flavours and test it. Notice that at the moment, there is a question regarding passing the theme between the different modules, as they don't depend on each other so we can not share buildconfig files.
I alreayd have a workaround for this, but it needs to be discussed.

**What are the relevant tickets?**

  Tickets related to this pull-request: [APP-1310](https://aptoide.atlassian.net/browse/APP-1310)

**Questions:**

   Does this add new dependencies which need to be added? (Eg. new keys, etc.) 

**Code Review Checklist**

- [ ] Documentation on public interfaces
- [ ] Database changed? If yes - Migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] New Kotlin code has unit tests
- [ ] New flows in presenters unit tests
- [ ] Mappers/Validators with any kind of logic unit tests
- [ ] Functional tests pass

2022-09-06 13:57 UTC, jdandrade requested changes
Switching from cobrand to vanilla in the :app module will change every module entry to vanilla BUT :feature-profile, can we fix it?

2022-09-06 13:57 UTC, jdandrade commented on aptoide-ui/src/main/java/cm/aptoide/pt/aptoide_ui/theme/Theme.kt
> +  return if (baseTheme == "cobrand") {
can't we use always the same config file but branched in different folders (vanilla & cobrand)?

2022-09-06 14:34 UTC, phillipsgoncalves commented on app/build.gradle.kts
> +        "com.aptoide.partners." + project.properties["COBRAND_APPLICATION_ID_SUFFIX"].toString()
waiting for ana response

2022-09-07 10:30 UTC, jdandrade approved these changes

2022-09-07 10:31 UTC, merged