[DT-336] Profile View Refactor
Aptoide/aptoide-client-v8 pull request #1649
Opened 2023-06-09 10:59 UTC by AngeloMendonca

**What does this PR do?**

   Refactor the profile view following the settings view structure

**Database changed?**

   No

**Where should the reviewer start?**

- [ ] by commits

**How should this be manually tested?**

  Flow on how to test this or QA Tickets related to this use-case: [DT-336](https://aptoide.atlassian.net/browse/DT-336)

**What are the relevant tickets?**

  Tickets related to this pull-request: [DT-336](https://aptoide.atlassian.net/browse/DT-336)

**Code Review Checklist**

- [ ] Documentation on public interfaces
- [ ] Database changed? If yes - Migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] New Kotlin code has unit tests
- [ ] New flows in presenters unit tests
- [ ] Mappers/Validators with any kind of logic unit tests
- [ ] Functional tests pass

2023-06-09 13:38 UTC, G0retZ requested changes

2023-06-09 13:38 UTC, G0retZ commented on feature-profile/src/main/java/cm/aptoide/pt/profile/presentation/ProfileView.kt
> +
unnecessary new line

2023-06-09 13:38 UTC, G0retZ commented on feature-profile/src/main/java/cm/aptoide/pt/profile/presentation/ProfileView.kt
> +
unnecessary new line

2023-06-09 13:38 UTC, G0retZ commented on feature-profile/src/main/java/cm/aptoide/pt/profile/presentation/ProfileView.kt
> +
unnecessary new line

2023-06-09 13:38 UTC, G0retZ commented on feature-profile/src/main/java/cm/aptoide/pt/profile/presentation/ProfileView.kt
> +
unnecessary new line

2023-06-09 13:38 UTC, G0retZ commented on feature-profile/src/main/java/cm/aptoide/pt/profile/presentation/ProfileView.kt
> +
unnecessary new line

2023-06-09 13:38 UTC, G0retZ commented on feature-profile/src/main/java/cm/aptoide/pt/profile/presentation/ProfileView.kt
> +
unnecessary new line

2023-06-09 13:38 UTC, G0retZ commented on feature-profile/src/main/java/cm/aptoide/pt/profile/presentation/ProfileView.kt
> +
unnecessary new line

2023-06-09 13:38 UTC, G0retZ commented on feature-profile/src/main/java/cm/aptoide/pt/profile/presentation/ProfileView.kt
> +
unnecessary new line

2023-06-09 13:38 UTC, G0retZ commented on feature-profile/src/main/java/cm/aptoide/pt/profile/presentation/ProfileView.kt
> +
unnecessary new line

2023-06-09 13:38 UTC, G0retZ commented on feature-profile/src/main/java/cm/aptoide/pt/profile/presentation/ProfileView.kt
> +
unnecessary new line

2023-06-09 13:38 UTC, G0retZ commented on feature-profile/src/main/java/cm/aptoide/pt/profile/presentation/ProfileView.kt
> +
unnecessary new line

2023-06-09 13:38 UTC, G0retZ commented on feature-profile/src/main/java/cm/aptoide/pt/profile/presentation/ProfileView.kt
> +
unnecessary new line

2023-06-09 13:38 UTC, G0retZ commented on feature-profile/src/main/java/cm/aptoide/pt/profile/presentation/ProfileView.kt
> +private fun FollowUsIcon(
Function name is misleading

2023-06-12 08:57 UTC, AngeloMendonca commented on feature-profile/src/main/java/cm/aptoide/pt/profile/presentation/ProfileView.kt
> +    Spacer(modifier = Modifier.width(1.dp))
For no reason, i don't know why i used it in the first place xD

2023-06-12 13:19 UTC, G0retZ approved these changes

2023-06-12 13:26 UTC, merged