[DT-529] Add support for deferred install tasks and add long extensions
Aptoide/aptoide-client-v8 pull request #1696
Opened 2023-09-14 17:23 UTC by pedroagostinhoaptoide

**What does this PR do?**

   - Adds support to deferred app installations, by adding the necessary logic in the install manager and App and Task implementations.
   - Adds long primitive type extension functions related to dealing with app sizes.

**Database changed?**

   No

**Where should the reviewer start?**

- See by commit.

**How should this be manually tested?**

  Flow on how to test this or QA Tickets related to this use-case: [DT-529](https://aptoide.atlassian.net/browse/DT-529)

**What are the relevant tickets?**

  Tickets related to this pull-request: [DT-529](https://aptoide.atlassian.net/browse/DT-529)

**Code Review Checklist**

- [ ] Documentation on public interfaces
- [ ] Database changed? If yes - Migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] New Kotlin code has unit tests
- [ ] New flows in presenters unit tests
- [ ] Mappers/Validators with any kind of logic unit tests
- [ ] Functional tests pass

2023-09-19 13:34 UTC, ricardo-frango requested changes

2023-09-19 13:34 UTC, ricardo-frango commented on install-manager/src/main/java/cm/aptoide/pt/install_manager/App.kt
> +  suspend fun install(
missing new params in java doc

2023-09-19 13:34 UTC, ricardo-frango commented on install-manager/src/main/java/cm/aptoide/pt/install_manager/RealTask.kt
> +  private val deferMe: suspend (RealTask) -> Unit,
unused property

2023-09-19 13:34 UTC, ricardo-frango commented on install-manager/src/main/java/cm/aptoide/pt/install_manager/RealTask.kt
> +    } catch (e: DeferDownloadException) {
this catch is empty

2023-09-19 13:34 UTC, ricardo-frango commented on install-manager/src/main/java/cm/aptoide/pt/install_manager/workers/PackageDownloader.kt
> +  suspend fun download(
missing new param in java doc

2023-09-25 08:16 UTC, G0retZ requested changes
Rebase on `dev-v10`

2023-09-25 08:16 UTC, G0retZ commented on install-manager/src/main/java/cm/aptoide/pt/install_manager/App.kt
> +   * @param onTerminate - called after installation is finished with success
The description is misleading

2023-09-26 07:43 UTC, G0retZ commented on download-view/src/main/java/cm/aptoide/pt/download_view/presentation/DownloadView.kt
This change should be in a previous commit

2023-09-26 07:50 UTC, G0retZ approved these changes

2023-09-26 09:48 UTC, ricardo-frango approved these changes

2023-09-26 15:46 UTC, merged