[DT-1130] Decouple submodule build system from the project one
Aptoide/aptoide-client-v8 pull request #1776
Opened 2024-02-29 15:08 UTC by ricardo-frango

**What does this PR do?**

   Decoupled the payment modules dependencies on the buildSrc module.
   Also added the meterial to the uri handler module because of the activity theme that must be MaterialComponents and it was missing because of the compose removal.

**Database changed?**

   No

**Where should the reviewer start?**

- [ ] build.gradle.kts
- [ ] settings.gradle.kts

**How should this be manually tested?**

  Flow on how to test this or QA Tickets related to this use-case: [APP-1130](https://aptoide.atlassian.net/browse/DT-1130)

**What are the relevant tickets?**

  Tickets related to this pull-request: [APP-1130](https://aptoide.atlassian.net/browse/DT-1130)

**Code Review Checklist**

- [ ] Documentation on public interfaces
- [ ] Database changed? If yes - Migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] New Kotlin code has unit tests
- [ ] New flows in presenters unit tests
- [ ] Mappers/Validators with any kind of logic unit tests
- [ ] Functional tests pass

2024-03-05 16:29 UTC, ricardo-frango commented on payments/versions.gradle.kts
> +val defaultMinSdkVersion by extra { 26 }
this might have impact in current payments implementation.
maybe it should be done in a different ticket

2024-03-05 16:30 UTC, ricardo-frango commented on payments/payment-methods/adyen-compose/build.gradle.kts
> +  implementation("io.coil-kt:coil-compose:$coilComposeVersion")
these changes were done based on the gradle plugins implementation.
maybe cleaning unused dependencies should be done in a different ticket.

2024-03-08 10:11 UTC, G0retZ requested changes
Lets also clean up the gradle files in terms of `api` vs `implementation`

2024-03-08 10:11 UTC, G0retZ commented on payments/payment-methods/adyen/src/main/java/com/appcoins/payment_method/adyen/repository/AdyenV2Repository.kt
> -  return JsonParser().parse(this.toString()).asJsonObject
You can drop this change, in PR it is removed

2024-03-08 10:11 UTC, G0retZ commented on payments/base/arch/build.gradle.kts
> +  lint {
Lets remove these blocks as they are irrelevant for payments

2024-03-08 10:11 UTC, G0retZ commented on payments/base/arch/build.gradle.kts
> +fun getVersionFor(
Can we extract it to `../../versions.gradle.kts`?
Also the default values names have the same `default` prefix. Mb we can you this fact to reduce number of arguments and just add `default_` prefix to the `versionName` value name to get dependency? 🤔

2024-03-11 07:39 UTC, G0retZ approved these changes

2024-03-11 09:35 UTC, merged