[App-2465] Update UI of the see more screen with the items
Aptoide/aptoide-client-v8 pull request #1845
Opened 2024-05-17 11:54 UTC by ricardo-frango

**What does this PR do?**

   Updated the "See all" section.
   Also update the installation progress text.

**Database changed?**

   No

**Where should the reviewer start?**

- [ ] MoreBundleView.kt
- [ ] ProgressText.kt

**How should this be manually tested?**

  Flow on how to test this or QA Tickets related to this use-case: [APP-2465](https://aptoide.atlassian.net/browse/APP-2465)

**What are the relevant tickets?**

  Tickets related to this pull-request: [APP-2465](https://aptoide.atlassian.net/browse/APP-2465)

**Code Review Checklist**

- [ ] Documentation on public interfaces
- [ ] Database changed? If yes - Migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] New Kotlin code has unit tests
- [ ] New flows in presenters unit tests
- [ ] Mappers/Validators with any kind of logic unit tests
- [ ] Functional tests pass

[APP-2465]: https://aptoide.atlassian.net/browse/APP-2465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-2465]: https://aptoide.atlassian.net/browse/APP-2465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-05-20 12:21 UTC, G0retZ requested changes

2024-05-20 12:21 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/MoreBundleView.kt
>  @PreviewAll
Lets use `PreviewDark`

2024-05-20 12:21 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/MoreBundleView.kt
> +@PreviewAll
Lets use `PreviewDark`

2024-05-20 12:21 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/MoreBundleView.kt
> -    AppsListUiState.Idle(List(size = Random.nextInt(15)) { randomApp }),
Can we avoid this change?

2024-05-20 12:21 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/installer/presentation/ProgressText.kt
> +  ProgressTextContent(app = app, state = state, showVersionName = showVersionName)
Put arguments on separate lines

2024-05-20 12:21 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/installer/presentation/ProgressText.kt
> +        style = AppTheme.typography.body,
In Figma it's `inputs_S` for all cases

2024-05-20 12:21 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/installer/presentation/ProgressText.kt
> +@PreviewAll
Lets use `PreviewDark`

2024-05-20 12:21 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/installer/presentation/ProgressText.kt
> +@PreviewAll
Lets use `PreviewDark`

2024-05-20 12:21 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/installer/presentation/ProgressText.kt
> +@PreviewAll
Lets use `PreviewDark`

2024-05-20 12:23 UTC, G0retZ requested changes
Installation button doesn't work in SeeMore screen. It immediately reports error instead of download start...

2024-05-20 15:43 UTC, G0retZ approved these changes

2024-05-20 16:28 UTC, pedroagostinhoaptoide requested changes
Change the text style of the app items to match the design

2024-05-21 09:05 UTC, pedroagostinhoaptoide approved these changes

2024-05-21 09:16 UTC, merged