[APP-2347] Settings billing terms of use url
Aptoide/aptoide-client-v8 pull request #1886
Opened 2024-06-17 11:46 UTC by Culurio

**What does this PR do?**

This PR aims to add a URL to billing terms on settings

**Database changed?**

   No

**Where should the reviewer start?**

- [ ] LegalUrls.kt
- [ ] build.gradle.kts
- [ ] SettingsScreen.kt

**How should this be manually tested?**

  Flow on how to test this or QA Tickets related to this use-case: [APP-2347](https://aptoide.atlassian.net/browse/APP-2347)

**What are the relevant tickets?**

  Tickets related to this pull-request: [APP-2347](https://aptoide.atlassian.net/browse/APP-2347)

**Questions:**

   Does this add new dependencies which need to be added? (Eg. new keys, etc.) 

**Code Review Checklist**

- [ ] Documentation on public interfaces
- [ ] Database changed? If yes - Migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] New Kotlin code has unit tests
- [ ] New flows in presenters unit tests
- [ ] Mappers/Validators with any kind of logic unit tests
- [ ] Functional tests pass

2024-06-17 11:46 UTC, apkbuilder-lw commented
Can one of the admins verify this patch?

2024-06-18 15:22 UTC, ricardo-frango requested changes

2024-06-18 15:22 UTC, ricardo-frango commented on app-games/src/main/java/com/aptoide/android/aptoidegames/settings/SettingsScreen.kt
> +    onBillingTermsClick = {UrlActivity.open(context, context.btUrl)},
fix code spacing

2024-06-19 12:21 UTC, ricardo-frango approved these changes

2024-06-20 08:41 UTC, merged