[APP-2578] Settings contact support
Aptoide/aptoide-client-v8 pull request #1887
Opened 2024-06-17 12:00 UTC by Culurio

**What does this PR do?**
This PR aims to add behaviour when clicking “Contact Support Team”

**Database changed?**

  No

**Where should the reviewer start?**

- [ ] See by commit

**How should this be manually tested?**

  Flow on how to test this or QA Tickets related to this use-case: [APP-2578](https://aptoide.atlassian.net/browse/APP-2578)

**What are the relevant tickets?**

  Tickets related to this pull-request: [APP-2578](https://aptoide.atlassian.net/browse/APP-2578)

**Questions:**

   Does this add new dependencies which need to be added? (Eg. new keys, etc.) 

**Code Review Checklist**

- [ ] Documentation on public interfaces
- [ ] Database changed? If yes - Migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] New Kotlin code has unit tests
- [ ] New flows in presenters unit tests
- [ ] Mappers/Validators with any kind of logic unit tests
- [ ] Functional tests pass

2024-06-17 12:00 UTC, apkbuilder-lw commented
Can one of the admins verify this patch?

2024-06-18 13:35 UTC, GuiFPires requested changes

2024-06-19 16:24 UTC, GuiFPires requested changes

2024-06-19 16:24 UTC, GuiFPires commented on app-games/src/main/java/com/aptoide/android/aptoidegames/SupportActivity.kt
Add the //TODO Hardcoded String on the temporary strings

2024-06-20 15:35 UTC, GuiFPires approved these changes

2024-06-21 08:20 UTC, merged