[APP-2545] Copy Firebase analytics from GH
Aptoide/aptoide-client-v8 pull request #1901
Opened 2024-06-25 08:52 UTC by G0retZ

**What does this PR do?**

   Copies and adapts Firebase analytics from GH. 

   Found and fixed some issues. Also had to refactor some code for more convenient analytics integration.

**Database changed?**

   No

**Where should the reviewer start?**

- [ ] By commits

**How should this be manually tested?**

  Flow on how to test this or QA Tickets related to this use-case: [APP-2545](https://aptoide.atlassian.net/browse/APP-2545)

**What are the relevant tickets?**

  Tickets related to this pull-request: [APP-2545](https://aptoide.atlassian.net/browse/APP-2545)

**What are the relevant PRs?**

  PRs related to this one: [#531](https://github.com/Aptoide/aptoide-client-dt/pull/531)  [#2](https://github.com/Catappult/appcoins-payments-android/pull/2)

**Code Review Checklist**

- [ ] Documentation on public interfaces
- [ ] Database changed? If yes - Migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] New Kotlin code has unit tests
- [ ] New flows in presenters unit tests
- [ ] Mappers/Validators with any kind of logic unit tests
- [ ] Functional tests pass

2024-06-26 09:34 UTC, GuiFPires requested changes

2024-06-26 09:34 UTC, GuiFPires commented on app-games/src/main/java/com/aptoide/android/aptoidegames/analytics/presentation/AnalyticsContext.kt
Apply code style

2024-06-26 09:34 UTC, GuiFPires commented on app-games/src/main/java/com/aptoide/android/aptoidegames/AptoideApplication.kt
Apply code style

2024-06-26 09:34 UTC, GuiFPires commented on app-games/src/main/java/com/aptoide/android/aptoidegames/categories/presentation/CategoriesView.kt
Apply code style

2024-06-26 09:34 UTC, GuiFPires commented on app-games/src/main/java/com/aptoide/android/aptoidegames/installer/presentation/InstallViewStates.kt
Apply code style

2024-06-26 09:34 UTC, GuiFPires commented on app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/payment_methods/LandscapePaymentView.kt
Apply code style

2024-06-26 09:34 UTC, GuiFPires commented on app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/MoreBundleView.kt
Apply code style

2024-06-26 09:34 UTC, GuiFPires commented on app-games/src/main/java/com/aptoide/android/aptoidegames/notifications/NotificationsPermissionRequester.kt
Apply code style

2024-06-26 09:34 UTC, GuiFPires commented on app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/payment_methods/PortraitPaymentView.kt
Apply code style

2024-06-26 09:34 UTC, GuiFPires commented on app-games/src/main/java/com/aptoide/android/aptoidegames/network/AptoideGetHeaders.kt
> +  override val channel: String = "ANDROID"
leave it as "aptoide-games"

2024-06-27 09:11 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/network/AptoideGetHeaders.kt
> +  override val channel: String = "ANDROID"
Fixed

2024-06-27 09:11 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/payment_methods/PortraitPaymentView.kt
Applied

2024-06-27 09:11 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/notifications/NotificationsPermissionRequester.kt
Applied

2024-06-27 09:11 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/MoreBundleView.kt
Applied

2024-06-27 09:11 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/feature_payments/payment_methods/LandscapePaymentView.kt
Applied

2024-06-27 09:11 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/installer/presentation/InstallViewStates.kt
Applied

2024-06-27 09:12 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/categories/presentation/CategoriesView.kt
Applied

2024-06-27 09:12 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/AptoideApplication.kt
Applied

2024-06-27 09:12 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/analytics/presentation/AnalyticsContext.kt
Applied

2024-06-27 10:10 UTC, GuiFPires approved these changes

2024-06-27 14:54 UTC, GuiFPires approved these changes

2024-06-27 15:32 UTC, ricardo-frango requested changes

2024-06-28 08:11 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/analytics/presentation/SwipeListener.kt
> +  val (numberOfSwipes, setNumberOfSwipes) = remember { mutableStateOf(0) }
Fixed

2024-06-28 08:20 UTC, GuiFPires approved these changes

2024-06-28 09:47 UTC, merged