[APP-2614] Aptoide games APKFY flow implementation
Aptoide/aptoide-client-v8 pull request #1918
Opened 2024-07-02 15:37 UTC by pedroagostinhoaptoide

**What does this PR do?**

   - Adds the AptoideGames APKFY flow implementation, including the bottom sheet that follows the design.
   - Changes the getMeta call to be able to fetch an app by app id.

**Database changed?**

   No

**Where should the reviewer start?**

- [ ] See by commit.

**How should this be manually tested?**

  1.   Run the /download endpoint in the Aptoide MMP OpenAPI, with the package name of the app you want to test and an oemID.
  2. Perform a clean install on the app and check if the apkfy flow starts correctly and the bottom sheet shows up.

  Flow on how to test this or QA Tickets related to this use-case: [APP-2614](https://aptoide.atlassian.net/browse/APP-2614)

**What are the relevant tickets?**

  Tickets related to this pull-request: [APP-2614](https://aptoide.atlassian.net/browse/APP-2614)

**Code Review Checklist**

- [ ] Documentation on public interfaces
- [ ] Database changed? If yes - Migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] New Kotlin code has unit tests
- [ ] New flows in presenters unit tests
- [ ] Mappers/Validators with any kind of logic unit tests
- [ ] Functional tests pass

2024-07-03 11:22 UTC, Culurio approved these changes

2024-07-09 15:35 UTC, GuiFPires requested changes

2024-07-09 15:35 UTC, GuiFPires commented on feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/AptoideAppsRepository.kt
Apply Code Style

2024-07-09 15:35 UTC, GuiFPires commented on feature_apps/src/main/java/cm/aptoide/pt/feature_apps/domain/AppMetaUseCase.kt
Apply Code Style

2024-07-09 15:35 UTC, GuiFPires commented on feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/AppsRepository.kt
Apply Code Style

2024-07-09 15:35 UTC, GuiFPires commented on app-games/src/main/java/com/aptoide/android/aptoidegames/apkfy/ApkfyViewModel.kt
> +import timber.log.Timber
Remove Unused Import

2024-07-09 15:35 UTC, GuiFPires commented on app-games/src/main/java/com/aptoide/android/aptoidegames/AptoideGamesBottomSheet.kt
Remove Unused Imports

2024-07-16 16:34 UTC, GuiFPires approved these changes

2024-07-17 11:22 UTC, merged