[APP-2625] Fix out of space calculations
Aptoide/aptoide-client-v8 pull request #1922
Opened 2024-07-08 09:24 UTC by G0retZ

**What does this PR do?**

   Fixes the out of space prediction calculations by excluding cancelled and uninstallation tasks files from it. 

   Had to refactor the out-of-space logic in general to make it testable first. The faulty case is now covered by tests also.

**Database changed?**

   No

**Where should the reviewer start?**

- [ ] By commits

**How should this be manually tested?**

  Flow on how to test this or QA Tickets related to this use-case: [APP-2625](https://aptoide.atlassian.net/browse/APP-2625)

**What are the relevant tickets?**

  Tickets related to this pull-request: [APP-2625](https://aptoide.atlassian.net/browse/APP-2625)

**What are the relevant PRs?**

  PRs related to this one: [#536](https://github.com/Aptoide/aptoide-client-dt/pull/536)

**Code Review Checklist**

- [ ] Documentation on public interfaces
- [ ] Database changed? If yes - Migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] New Kotlin code has unit tests
- [ ] New flows in presenters unit tests
- [ ] Mappers/Validators with any kind of logic unit tests
- [ ] Functional tests pass

2024-07-09 08:45 UTC, GuiFPires requested changes

2024-07-11 08:57 UTC, G0retZ commented on install-manager/src/test/java/cm/aptoide/pt/install_manager/AppTest.kt
> +import org.junit.jupiter.api.Assertions.assertTrue
fixed

2024-07-11 08:57 UTC, G0retZ commented on download-view/src/main/java/cm/aptoide/pt/download_view/presentation/DownloadViewModel.kt
fixed

2024-07-11 10:24 UTC, GuiFPires approved these changes

2024-07-15 07:13 UTC, merged