[APP-2512] Change AG permissions
Aptoide/aptoide-client-v8 pull request #1955
Opened 2024-08-26 08:23 UTC by pedroagostinhoaptoide

**What does this PR do?**

   - Changes the AG external storage permissions logic, to make the rationale show only after the second try.
   - Changes the AG permissions rationale dialog design.

**Database changed?**

   No

**Where should the reviewer start?**

- [ ] See by commit.

**How should this be manually tested?**

  Flow on how to test this or QA Tickets related to this use-case: [APP-2512](https://aptoide.atlassian.net/browse/APP-2512)

**What are the relevant tickets?**

  Tickets related to this pull-request: [APP-2512](https://aptoide.atlassian.net/browse/APP-2512)

**Code Review Checklist**

- [ ] Documentation on public interfaces
- [ ] Database changed? If yes - Migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] New Kotlin code has unit tests
- [ ] New flows in presenters unit tests
- [ ] Mappers/Validators with any kind of logic unit tests
- [ ] Functional tests pass

2024-08-26 13:15 UTC, GuiFPires requested changes

2024-08-26 13:15 UTC, GuiFPires commented on app-games/src/main/java/com/aptoide/android/aptoidegames/permissions/notifications/NotificationsPermissionViewModel.kt
Apply Code Style

2024-08-27 08:40 UTC, pedroagostinhoaptoide commented on app-games/src/main/java/com/aptoide/android/aptoidegames/installer/UserActionDialog.kt
> +      PrimaryTextButton(
Added the padding to the column surrounding the buttons

2024-08-27 14:10 UTC, G0retZ requested changes

2024-08-27 14:10 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/permissions/AppPermissionsManager.kt
> +class AppPermissionsManager @Inject constructor(
Looks like a candidate to spilt into a single interface and 2 implementations...

2024-08-28 08:57 UTC, G0retZ approved these changes

2024-08-28 09:07 UTC, phillipsgoncalves approved these changes

2024-08-28 14:38 UTC, merged