[APP-2865] Navigation by app id
Aptoide/aptoide-client-v8 pull request #1972
Opened 2024-09-03 17:48 UTC by pedroagostinhoaptoide

**What does this PR do?**

   - Changes AppViewScreen navigation to use app id instead of package name when possible.
   - Removes the flag that controls store name usage on app meta requests. The store name is now only appended when the request is done with anything other than app id.
   - Makes the installer notifications use app id instead of package name when creating the deeplink to navigate to the app.

**Database changed?**

   Yes - changed the AppDetails database in order to include the app id. It will be the app id of the version for which an installation was started.

**Where should the reviewer start?**

- [ ] See by commit.

**How should this be manually tested?**

  **Every flow that goes into the app view should be tested. That includes navigating from:**

1. Home Screen
2. See all screens
3. Ahab - atm only notifications
4. APKFY

  Flow on how to test this or QA Tickets related to this use-case: [APP-2865](https://aptoide.atlassian.net/browse/APP-2865)

**What are the relevant tickets?**

  Tickets related to this pull-request: [APP-2865](https://aptoide.atlassian.net/browse/APP-2865)

**Code Review Checklist**

- [ ] Documentation on public interfaces
- [ ] Database changed? If yes - Migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] New Kotlin code has unit tests
- [ ] New flows in presenters unit tests
- [ ] Mappers/Validators with any kind of logic unit tests
- [ ] Functional tests pass

2024-09-04 16:38 UTC, GuiFPires reviewed
Shouldn't the json file be committed as well?

2024-09-05 08:45 UTC, GuiFPires approved these changes

2024-09-06 13:25 UTC, G0retZ requested changes

2024-09-06 13:25 UTC, G0retZ commented on feature_apps/src/main/java/cm/aptoide/pt/feature_apps/presentation/ViewModelProvider.kt
> +fun rememberAppBySource(source: String): Pair<AppUiState, () -> Unit> = runPreviewable(
Lets make the same migration for `v10` and remove this function, leaving only `rememberApp` that returns by source

2024-09-06 13:25 UTC, G0retZ commented on feature_apps/src/main/java/cm/aptoide/pt/feature_apps/domain/AppMetaUseCase.kt
> +  suspend fun getMetaInfoBySource(source: String): App =
Lets call it just `getMetaInfo`

2024-09-06 13:25 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/appview/AppViewScreen.kt
> +fun buildAppViewRouteByAppId(appId: Long): String = buildAppViewRouteBySource(appId.toAppIdParam())
Lets rename this to simple `buildAppViewRoute`

2024-09-06 13:25 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/appview/AppViewScreen.kt
> +fun buildAppViewRouteBySource(source: String): String = appViewRoute.replace("{$SOURCE}", source)
Lets rename this to simple `buildAppViewRoute`

2024-09-06 13:25 UTC, G0retZ commented on feature_apps/src/main/java/cm/aptoide/pt/feature_apps/presentation/ViewModelProvider.kt
> +fun String.appendStoreName(storeName: String) =
Lets have extensions `asSource` for corresponding classes in addition to these on primitives

2024-09-13 08:26 UTC, G0retZ requested changes

2024-09-13 08:26 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/apkfy/analytics/ApkfyManagerProbe.kt
> +}
Missing new line

2024-09-13 08:26 UTC, G0retZ commented on feature-mmp/src/main/java/cm/aptoide/pt/feature_mmp/apkfy/di/RepositoryModule.kt
>    fun provideApkfyManager(
Do we still need this?

2024-09-13 08:26 UTC, G0retZ commented on feature_apps/src/main/java/cm/aptoide/pt/feature_apps/presentation/ViewModelProvider.kt
> +fun String.appendStoreName(storeName: String) =
Still can we encapsulate this?

2024-09-13 08:26 UTC, G0retZ commented on feature-apkfy/src/main/java/cm/aptoide/pt/feature_apkfy/di/RepositoryModule.kt
> +  fun provideApkfyManager(
Is this necessary?

2024-09-13 08:26 UTC, G0retZ commented on feature_apps/src/main/java/cm/aptoide/pt/feature_apps/domain/AppMetaUseCase.kt
> +  suspend fun getMetaInfo(source: String): App =
Why do we need both of these functions? 🤔

2024-09-13 08:26 UTC, G0retZ commented on feature_apps/src/main/java/cm/aptoide/pt/feature_apps/domain/AppMetaUseCase.kt
> +  suspend fun getMetaInfo(appSource: AppSource): App = getMetaInfo(source = appSource.asSource())
Why do we need both of these functions? 🤔

2024-09-16 11:12 UTC, merged