[APP-2881] Add whats new to app view
Aptoide/aptoide-client-v8 pull request #1987
Opened 2024-09-12 09:19 UTC by Culurio

**What does this PR do?**

This PR aims to add the what's new box to the App View

**Database changed?**

   No

**Where should the reviewer start?**

- [ ] See by commit

**How should this be manually tested?**

  Flow on how to test this or QA Tickets related to this use-case: [APP-2881](https://aptoide.atlassian.net/browse/APP-2881)

**What are the relevant tickets?**

  Tickets related to this pull-request: [APP-2881](https://aptoide.atlassian.net/browse/APP-2881)

**Questions:**

   Does this add new dependencies which need to be added? (Eg. new keys, etc.) 

**Code Review Checklist**

- [ ] Documentation on public interfaces
- [ ] Database changed? If yes - Migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] New Kotlin code has unit tests
- [ ] New flows in presenters unit tests
- [ ] Mappers/Validators with any kind of logic unit tests
- [ ] Functional tests pass

2024-09-13 10:22 UTC, G0retZ requested changes

2024-09-13 10:22 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/appview/AppViewScreen.kt
> +            .fillMaxWidth(),
Can be on a single line

2024-09-13 10:22 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/icons/BookmarkStar.kt
> +  name = "BookmarkStar", defaultWidth = 16.0.dp, defaultHeight =
Put arguments on separate lines

2024-09-13 10:22 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/icons/BookmarkStar.kt
> +      fill = SolidColor(color), stroke = null, strokeLineWidth = 0.0f,
Put arguments on separate lines

2024-09-13 10:22 UTC, G0retZ commented on feature_apps/src/main/java/cm/aptoide/pt/feature_apps/data/AptoideAppsRepository.kt
> +  news = if (this.media?.news.isNullOrEmpty()) null
Add curly braces or make this if-else expression in a single line

2024-09-16 09:13 UTC, G0retZ requested changes

2024-09-16 09:13 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/drawables/icons/BookmarkStar.kt
> +  defaultHeight =
I guess this line break is a typo? 🤔

2024-09-16 09:41 UTC, G0retZ approved these changes

2024-09-16 12:07 UTC, pedroagostinhoaptoide requested changes

2024-09-16 12:07 UTC, pedroagostinhoaptoide commented on app-games/src/main/java/com/aptoide/android/aptoidegames/appview/AppViewScreen.kt
> +      Row(
To fully match the design, the last text could be aligned to be centered vertically and the first two texts could be aligned by their baselines (with the `alignByBaseline` modifier)

2024-09-17 14:58 UTC, pedroagostinhoaptoide approved these changes

2024-09-17 14:59 UTC, merged