[APP-2816] Appc badge
Aptoide/aptoide-client-v8 pull request #1994
Opened 2024-09-17 13:24 UTC by Culurio

**What does this PR do?**

This PR implements functionality to make the Bonus badge clickable, redirecting users to the bonus page.

**Database changed?**

   No

**Where should the reviewer start?**

- [ ] See by commit

**How should this be manually tested?**

  Flow on how to test this or QA Tickets related to this use-case: [APP-2816](https://aptoide.atlassian.net/browse/APP-2816)

**What are the relevant tickets?**

  Tickets related to this pull-request: [APP-2816](https://aptoide.atlassian.net/browse/APP-2816)

**Questions:**

   Does this add new dependencies which need to be added? (Eg. new keys, etc.) 

**Code Review Checklist**

- [ ] Documentation on public interfaces
- [ ] Database changed? If yes - Migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] New Kotlin code has unit tests
- [ ] New flows in presenters unit tests
- [ ] Mappers/Validators with any kind of logic unit tests
- [ ] Functional tests pass

2024-09-17 14:10 UTC, GuiFPires requested changes
There are two other use cases that might be worth taking a look (better to check with João/Ana as well)

- If we are on the bonus view already, clicking on the badge infinitely will lead to a loop
- A similar case happens with the apkfy bottom sheet, as the sheet isn't dismissed (I don't know if it should be or not, as when we click the app icon it is) when we click the badge, we can navigate infinite times to the bonus page

2024-09-17 14:10 UTC, GuiFPires commented on app-games/src/main/java/com/aptoide/android/aptoidegames/search/presentation/SearchView.kt
Missing the navigate here on LargeAppItem

2024-09-17 16:35 UTC, GuiFPires requested changes

2024-09-17 16:35 UTC, GuiFPires commented on app-games/src/main/java/com/aptoide/android/aptoidegames/categories/presentation/CategoryDetailView.kt
Also missing navigate on LargeAppItem here

2024-09-18 14:51 UTC, GuiFPires approved these changes

2024-09-19 08:59 UTC, G0retZ requested changes

2024-09-19 08:59 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/appview/AppViewScreen.kt
> +      val bonusTitle = "Bonus"
Hardcoded string. Probably should be either translated recourse or fetched from network

2024-09-19 08:59 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/appview/AppViewScreen.kt
> +      val bonusTag = "bonus-banner"
I see these string literals repeated 7 times and all are connected with `getBonusIconLeft`.
Let's extract those as a reusable component to encapsulate these constants and not repeat them.

2024-09-24 11:40 UTC, GuiFPires requested changes
If we open an appview via deeplink and the app is closed, the app crashes due to the lateinit vars of bundleTitle and bundleTag not being initialized for the BonusData

2024-09-24 12:58 UTC, G0retZ requested changes

2024-09-24 12:58 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/appview/AppViewScreen.kt
> +      val bonusViewModel = BonusViewModel()
You should not instantiate view models on recompositons.

2024-09-24 12:58 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/BonusSectionView.kt
> +  val bonusViewModel = BonusViewModel()
You should not instantiate view models on recompositons.

2024-09-24 12:58 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/BonusViewModel.kt
> +  fun rememberBonusData(): Pair<String, String> {
This is a wrong way to inject and use view model.
Refer the other view models and remember functions syntax and usage.

2024-09-24 12:58 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/BonusViewModel.kt
> +    viewModelScope.launch {
Why do you need a view model scope here?

2024-09-24 12:59 UTC, G0retZ requested changes

2024-09-24 12:59 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/BonusSectionView.kt
> +  bonusViewModel.addBundleData(bundle.title, bundle.tag)
As well as you should not call view model functions on recompositons.

2024-09-30 08:08 UTC, GuiFPires approved these changes

2024-10-01 09:34 UTC, G0retZ requested changes

2024-10-01 09:34 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/appview/AppViewScreen.kt
> +  val (bundleTitle, bundleTag) = rememberBonusBundle() ?: (null to null)
This looks weird.
Better us it without destructor like so:
`val bonusBundle = rememberBonusBundle()`

2024-10-01 09:34 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/appview/AppViewScreen.kt
> +            if (bundleTitle != null && bundleTag != null) {
This looks weird.
Better us it as a single value like so:
`if (bonusBundle != null)`

2024-10-01 09:34 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/BonusSectionView.kt
> +  val bonusViewModel = hiltViewModel<BonusViewModel>()
Better encapsulate the function into the `rememberBonusBundle` and use it here

2024-10-01 09:34 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/feature_apps/presentation/BonusViewModel.kt
> +    bonusInfo
Make a method encapsulation here for wider usage
`bonusInfo to bonusViewModel.addBundleData`

2024-10-04 15:45 UTC, GuiFPires requested changes

2024-10-04 15:45 UTC, GuiFPires commented on feature-bonus/build.gradle.kts
Missing EOF empty line

2024-10-04 15:45 UTC, GuiFPires commented on feature-bonus/.gitignore
Missing EOF empty line

2024-10-08 08:37 UTC, G0retZ approved these changes

2024-10-08 08:57 UTC, merged