[APP-2910] Refactor padding logic on screens with Bottom bar
Aptoide/aptoide-client-v8 pull request #2014
Opened 2024-10-09 17:03 UTC by Culurio

**What does this PR do?**

   This PR aims to refactor the padding logic on screens that use the bottom bar

**Database changed?**

   Yes | No

**Where should the reviewer start?**

- [ ] See by commit

**How should this be manually tested?**

  Flow on how to test this or QA Tickets related to this use-case: [APP-2910](https://aptoide.atlassian.net/browse/APP-2910)

**What are the relevant tickets?**

  Tickets related to this pull-request: [APP-2910](https://aptoide.atlassian.net/browse/APP-2910)

**Questions:**

   Does this add new dependencies which need to be added? (Eg. new keys, etc.) 

**Code Review Checklist**

- [ ] Documentation on public interfaces
- [ ] Database changed? If yes - Migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] New Kotlin code has unit tests
- [ ] New flows in presenters unit tests
- [ ] Mappers/Validators with any kind of logic unit tests
- [ ] Functional tests pass

2024-10-10 17:42 UTC, GuiFPires requested changes
Everything is cool and works fine, just fix the conflicts

2024-10-14 08:41 UTC, G0retZ requested changes

2024-10-14 08:41 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/home/MainView.kt
> +        Box {
Why did you remove this padding? Isn't it for the display cutouts? 🤔

2024-10-14 08:41 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/search/presentation/SearchView.kt
> +import com.aptoide.android.aptoidegames.search.SearchType.MANUAL
Let's keep imports as they were before

2024-11-26 09:45 UTC, merged