[AND-84] Implement List of Updates UI
Aptoide/aptoide-client-v8 pull request #2054
Opened 2024-10-30 13:40 UTC by Culurio

**What does this PR do?**

    *This is in draft because the strings are hardcoded*
   This PR aims to create a List of App's that need Updating
   
**Database changed?**

   No

**Where should the reviewer start?**

- [ ] UpdateScreen.kt
- [ ] BoltIcon.kt

**How should this be manually tested?**

  Flow on how to test this or QA Tickets related to this use-case: [AND-84](https://aptoide.atlassian.net/browse/AND-84)

**What are the relevant tickets?**

  Tickets related to this pull-request: [AND-84](https://aptoide.atlassian.net/browse/AND-84)

**Questions:**

   Does this add new dependencies which need to be added? (Eg. new keys, etc.) 

**Code Review Checklist**

- [ ] Documentation on public interfaces
- [ ] Database changed? If yes - Migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] New Kotlin code has unit tests
- [ ] New flows in presenters unit tests
- [ ] Mappers/Validators with any kind of logic unit tests
- [ ] Functional tests pass

2024-10-30 15:22 UTC, pedroagostinhoaptoide requested changes

2024-10-30 15:22 UTC, pedroagostinhoaptoide commented on app-games/src/main/java/com/aptoide/android/aptoidegames/updates/UpdatesScreen.kt
> +      .padding(start = 16.dp, end = 16.dp, top = 16.dp, bottom = 32.dp)
Use 16dp bottom padding for now, since each app item currently already has 16dp of top padding.

2024-10-30 15:22 UTC, pedroagostinhoaptoide commented on app-games/src/main/java/com/aptoide/android/aptoidegames/updates/UpdatesScreen.kt
> +    Column(
This column is not necessary

2024-10-30 15:22 UTC, pedroagostinhoaptoide commented on app-games/src/main/java/com/aptoide/android/aptoidegames/updates/UpdatesScreen.kt
> +        .semantics { collectionInfo = CollectionInfo(appList.size, 1) }
Even though there are no accessibility requirements, this semantics are wrong. The column and row info should be switched

2024-10-30 15:22 UTC, pedroagostinhoaptoide commented on app-games/src/main/java/com/aptoide/android/aptoidegames/updates/UpdatesScreen.kt
> +                .withItemPosition(index)
Fix newline

2024-10-30 15:22 UTC, pedroagostinhoaptoide commented on app-games/src/main/java/com/aptoide/android/aptoidegames/updates/UpdatesScreen.kt
> +      .fillMaxWidth(),
Fix newline

2024-10-31 09:46 UTC, pedroagostinhoaptoide commented on app-games/src/main/java/com/aptoide/android/aptoidegames/updates/UpdatesScreen.kt
> +        .semantics { collectionInfo = CollectionInfo(appList.size, 1) }
@Culurio this comment was wrong sorry, the change should be reverted 😅

2024-11-06 14:31 UTC, GuiFPires approved these changes

2024-11-06 15:29 UTC, G0retZ requested changes

2024-11-07 13:58 UTC, G0retZ approved these changes

2024-11-07 18:25 UTC, pedroagostinhoaptoide approved these changes

2024-11-07 18:25 UTC, merged