[AND-148] auto update in empty state
Aptoide/aptoide-client-v8 pull request #2092
Opened 2024-11-15 13:16 UTC by phillipsgoncalves

**What does this PR do?**

   This PR aims at implementing the auto update switch on the empty state of the updates.
Also took the oportunity to refactor the update flag view model.

**Database changed?**

 No

**Where should the reviewer start?**

- [ ] UpdatesScreen.kt

**How should this be manually tested?**

Open the section (with no updates -> or simply change the idle state to show the no updates screen as well) with auto update off, check if you see the toggle. Then turn on, reopen the view and check if you have the simple version of the empty screen

**What are the relevant tickets?**

  Tickets related to this pull-request: [AND-148](https://aptoide.atlassian.net/browse/AND-148)

**Questions:**

   Does this add new dependencies which need to be added? (Eg. new keys, etc.) 

**Code Review Checklist**

- [ ] Documentation on public interfaces
- [ ] Database changed? If yes - Migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] New Kotlin code has unit tests
- [ ] New flows in presenters unit tests
- [ ] Mappers/Validators with any kind of logic unit tests
- [ ] Functional tests pass

[AND-148]: https://aptoide.atlassian.net/browse/AND-148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-11-15 18:12 UTC, pedroagostinhoaptoide requested changes

2024-11-15 18:12 UTC, pedroagostinhoaptoide commented on app-games/src/main/java/com/aptoide/android/aptoidegames/updates/presentation/UpdatesScreen.kt
> +    if (showAutoUpdateToggle.value) {
Would it be easier to apply a spacer between the items instead of passing a padding as a parameter?

2024-11-15 18:12 UTC, pedroagostinhoaptoide commented on app-games/src/main/java/com/aptoide/android/aptoidegames/updates/presentation/UpdatesScreen.kt
> +      .defaultMinSize(minHeight = 48.dp)
Is this needed if minimumInteractiveComponentSize() is already used?

2024-11-15 18:43 UTC, GuiFPires approved these changes

2024-11-18 09:48 UTC, pedroagostinhoaptoide approved these changes

2024-11-18 09:52 UTC, merged