[AND-93] - Add AptoideMMP support to AppView AppLinks
Aptoide/aptoide-client-v8 pull request #2106
Opened 2024-11-19 17:39 UTC by GuiFPires

**What does this PR do?**

**In draft to confirm some details with Ana**
It adds the MMP logic coming from applinks to appview as described in the ticket.

**Database changed?**

 No

**Where should the reviewer start?**

- [ ] AppViewScreen.kt
- [ ] InstallViewStates.kt
- [ ] AptoideMMPCampaign.kt
- [ ] CampaignImpl.kt

**How should this be manually tested?**

  Flow on how to test this or QA Tickets related to this use-case: [AND-93](https://aptoide.atlassian.net/browse/AND-93)

**What are the relevant tickets?**

  Tickets related to this pull-request: [AND-93](https://aptoide.atlassian.net/browse/AND-93)

**Code Review Checklist**

- [ ] Documentation on public interfaces
- [ ] Database changed? If yes - Migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] New Kotlin code has unit tests
- [ ] New flows in presenters unit tests
- [ ] Mappers/Validators with any kind of logic unit tests
- [ ] Functional tests pass

2024-11-20 11:30 UTC, G0retZ requested changes

2024-11-20 12:01 UTC, GuiFPires commented on feature_campaigns/src/main/java/cm/aptoide/pt/feature_campaigns/CampaignImpl.kt
> +  var deepLinkUtms: Map<String, String>
Done

2024-11-20 12:34 UTC, G0retZ approved these changes

2024-11-25 14:30 UTC, G0retZ approved these changes

2024-11-25 14:30 UTC, merged