[AND-163] Add apkfy ab testing analytics
Aptoide/aptoide-client-v8 pull request #2130
Opened 2024-11-29 18:06 UTC by pedroagostinhoaptoide

**What does this PR do?**

   - Adds required firebase events for apkfy ab testing to work well.
   - Adds indicative user properties related to apkfy ab testing.

**Database changed?**

   No

**Where should the reviewer start?**

- [ ] See by commit.

**How should this be manually tested?**

  Flow on how to test this or QA Tickets related to this use-case: [AND-163](https://aptoide.atlassian.net/browse/AND-163)

**What are the relevant tickets?**

  Tickets related to this pull-request: [AND-163](https://aptoide.atlassian.net/browse/AND-163)

**Questions:**

   Does this add new dependencies which need to be added? (Eg. new keys, etc.) 

**Code Review Checklist**

- [ ] Documentation on public interfaces
- [ ] Database changed? If yes - Migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] New Kotlin code has unit tests
- [ ] New flows in presenters unit tests
- [ ] Mappers/Validators with any kind of logic unit tests
- [ ] Functional tests pass

2024-12-02 12:26 UTC, GuiFPires approved these changes

2024-12-03 10:43 UTC, G0retZ requested changes
Are we still missing the timeout related logic here? 🤔

2024-12-03 10:43 UTC, G0retZ commented on app-games/src/main/java/com/aptoide/android/aptoidegames/analytics/BIAnalytics.kt
> +    analyticsSender.setUserProperties(
Shouldn't this change be in @GuiFPires's PR? 🤔

2024-12-03 16:24 UTC, G0retZ approved these changes

2024-12-03 16:29 UTC, merged