[AND-193] Add Powered by AI
Aptoide/aptoide-client-v8 pull request #2155
Opened 2024-12-18 11:20 UTC by tomascarvalho7

**What does this PR do?**

Add powered by AI on top of the chat

**Database changed?**

   No

**Where should the reviewer start?**

- [ ] PoweredByAi.kt

**How should this be manually tested?**

Open GameGenie and check it's there

  Flow on how to test this or QA Tickets related to this use-case: [AND-193](https://aptoide.atlassian.net/browse/AND-193)

**What are the relevant tickets?**

  Tickets related to this pull-request: [AND-193](https://aptoide.atlassian.net/browse/AND-193)

**Questions:**

   Does this add new dependencies which need to be added? (Eg. new keys, etc.) 

**Code Review Checklist**

- [ ] Documentation on public interfaces
- [ ] Database changed? If yes - Migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] New Kotlin code has unit tests
- [ ] New flows in presenters unit tests
- [ ] Mappers/Validators with any kind of logic unit tests
- [ ] Functional tests pass

2024-12-18 11:20 UTC, apkbuilder-lw commented
Can one of the admins verify this patch?

2024-12-18 11:20 UTC, apkbuilder-lw commented
Can one of the admins verify this patch?

2024-12-18 15:35 UTC, phillipsgoncalves requested changes

2024-12-18 15:35 UTC, phillipsgoncalves commented on app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/composables/PoweredByAi.kt
> +      text = "Powered by AI",
hardcoded text, we are waiting for translations.

2024-12-18 15:35 UTC, phillipsgoncalves commented
Since the other 1st commit is here, i cant run because the commit is broken

2024-12-19 11:32 UTC, phillipsgoncalves commented
This pull request will be closed, since we are reviewing everything at the same time on :
https://github.com/Aptoide/aptoide-client-v8/pull/2156

This solution was adopted because all branches came out of each other so this way we can check everything in a row without having to solve conflicts or rebase 3 times.

2024-12-19 11:32 UTC, closed without merging