[AND-196] Add download speed to download analytics events
Aptoide/aptoide-client-v8 pull request #2158
Opened 2024-12-18 16:41 UTC by pedroagostinhoaptoide

**What does this PR do?**

   - Refactor Task State to include task progress
   - Changes the PackageDownloader interface and implementations so that it can emit more complex download info. It now returns not only the progress, but also the total number of downloaded bytes.
   - Adds the new download speed parameter to download analytics events.

**Database changed?**

   No

**Where should the reviewer start?**

See by commit.

**How should this be manually tested?**

  Flow on how to test this or QA Tickets related to this use-case: [AND-196](https://aptoide.atlassian.net/browse/AND-196)

**What are the relevant tickets?**

  Tickets related to this pull-request: [AND-196](https://aptoide.atlassian.net/browse/AND-196)

**Code Review Checklist**

- [ ] Documentation on public interfaces
- [ ] Database changed? If yes - Migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] New Kotlin code has unit tests
- [ ] New flows in presenters unit tests
- [ ] Mappers/Validators with any kind of logic unit tests
- [ ] Functional tests pass

2024-12-19 11:00 UTC, G0retZ requested changes

2024-12-19 11:00 UTC, G0retZ commented on install-manager/src/main/java/cm/aptoide/pt/install_manager/DownloadInfo.kt
> +data class DownloadInfo(
Looks like it is not used anywhere else than PackageDownloader implementations. And Task uses only progress value from it. How about using it also in the `Task.State.Downloading` state?

2024-12-20 09:57 UTC, pedroagostinhoaptoide commented on install-manager/src/main/java/cm/aptoide/pt/install_manager/RealTask.kt
> +    it::class.simpleName !in listOf(
Fixed

2024-12-20 09:57 UTC, pedroagostinhoaptoide commented on install-manager/src/main/java/cm/aptoide/pt/install_manager/DownloadInfo.kt
> +  val progress: Int = 0,
Fixed

2024-12-20 10:50 UTC, G0retZ commented on install-manager/src/main/java/cm/aptoide/pt/install_manager/DownloadInfo.kt
> +data class DownloadInfo(
Let's create a tech debt ticket about this

2024-12-20 10:50 UTC, G0retZ approved these changes

2024-12-20 10:55 UTC, merged