[AND-228] Implement GameGenie Suggestion Analytics
Aptoide/aptoide-client-v8 pull request #2168
Opened 2024-12-27 11:41 UTC by tomascarvalho7

**What does this PR do?**

Implement GameGenie Suggestion Analytics, making it possible to analyze which suggestions are being clicked by users

**Database changed?**

   No

**Where should the reviewer start?**

- [ ] SuggestionBox.kt

**How should this be manually tested?**

  Flow on how to test this or QA Tickets related to this use-case: [AND-228](https://aptoide.atlassian.net/browse/AND-228)

**What are the relevant tickets?**

  Tickets related to this pull-request: [AND-228](https://aptoide.atlassian.net/browse/AND-228)

**Questions:**

   Does this add new dependencies which need to be added? (Eg. new keys, etc.) 

**Code Review Checklist**

- [ ] Documentation on public interfaces
- [ ] Database changed? If yes - Migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] New Kotlin code has unit tests
- [ ] New flows in presenters unit tests
- [ ] Mappers/Validators with any kind of logic unit tests
- [ ] Functional tests pass

2024-12-27 11:41 UTC, apkbuilder-lw commented
Can one of the admins verify this patch?

2024-12-27 11:41 UTC, apkbuilder-lw commented
Can one of the admins verify this patch?

2024-12-27 16:42 UTC, phillipsgoncalves requested changes

2024-12-27 16:42 UTC, phillipsgoncalves commented on app-games/src/main/java/com/aptoide/android/aptoidegames/gamegenie/presentation/composables/MessageList.kt
> +          SuggestionBox(suggestion, onSuggestionClick, idx)
This index is the index of the message on the whole list of messages. Isnt the analytics about the index of the suggestion inside the suggestion list itself ?

2024-12-30 12:18 UTC, phillipsgoncalves approved these changes

2024-12-30 12:18 UTC, merged